=== jordanchenWM/DOH_maven/DOH_maven/target/DOH_maven/WEB-INF/classes/schema/MEDRCPTReply.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="ReceiptReply">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="MesgInfo" nillable="true" type="messageInformation"/>
        <xsd:element name="Header" nillable="true">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="DocInfo" nillable="true">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="AllianceID" nillable="true" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="DocNo" nillable="true" type="xsd:string"/>
                    <xsd:element name="ResponseTime" nillable="true" type="xsd:string" minOccurs="0"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="ReplyInfo" nillable="true">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Status" nillable="true" type="xsd:string"/>
                    <xsd:element name="Memo" nillable="true" type="xsd:string" minOccurs="0"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="CrossRateInfo" nillable="true" type="rec_receiptCrossRateInformation"/>
        <xsd:element name="UnitPriceInfo" nillable="true" type="rec_RCPTPrice"/>
        <xsd:element name="CCD_RCPT_RECOVERED" nillable="true" type="rec_CCDReocvered"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="MEDRCPTReply">
    <xsd:sequence>
      <xsd:element name="ReceiptReply" nillable="true">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="MesgInfo" nillable="true" type="messageInformation"/>
            <xsd:element name="Header" nillable="true">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="DocInfo" nillable="true">
                    <xsd:complexType>
                      <xsd:sequence>
                        <xsd:element name="AllianceID" nillable="true" type="xsd:string" minOccurs="0"/>
                        <xsd:element name="DocNo" nillable="true" type="xsd:string"/>
                        <xsd:element name="ResponseTime" nillable="true" type="xsd:string" minOccurs="0"/>
                      </xsd:sequence>
                    </xsd:complexType>
                  </xsd:element>
                  <xsd:element name="ReplyInfo" nillable="true">
                    <xsd:complexType>
                      <xsd:sequence>
                        <xsd:element name="Status" nillable="true" type="xsd:string"/>
                        <xsd:element name="Memo" nillable="true" type="xsd:string" minOccurs="0"/>
                      </xsd:sequence>
                    </xsd:complexType>
                  </xsd:element>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="CrossRateInfo" nillable="true" type="rec_receiptCrossRateInformation"/>
            <xsd:element name="UnitPriceInfo" nillable="true" type="rec_RCPTPrice"/>
            <xsd:element name="CCD_RCPT_RECOVERED" nillable="true" type="rec_CCDReocvered"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="messageInformation">
    <xsd:sequence>
      <xsd:element name="ProcessID" nillable="true" type="xsd:string"/>
      <xsd:element name="SenderID" nillable="true" type="xsd:string"/>
      <xsd:element name="ReceiverID" nillable="true" type="xsd:string"/>
      <xsd:element name="DocumentType" nillable="true" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="rec_receiptCrossRateInformation">
    <xsd:sequence>
      <xsd:element name="SourceReceiptNo" nillable="true" type="xsd:string"/>
      <xsd:element name="OldRate" nillable="true" type="xsd:string"/>
      <xsd:element name="NewRate" nillable="true" type="xsd:string"/>
      <xsd:element name="Accamt" nillable="true" type="xsd:string"/>
      <xsd:element name="SourceDisamt" nillable="true" type="xsd:string"/>
      <xsd:element name="Memo" nillable="true" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="rec_RCPTPrice">
    <xsd:sequence>
      <xsd:element name="UNRECEIPTNO" nillable="true" type="xsd:string"/>
      <xsd:element name="RECEIPTNO" nillable="true" type="xsd:string"/>
      <xsd:element name="HOSPID" nillable="true" type="xsd:string"/>
      <xsd:element name="HOSPRGNO" nillable="true" type="xsd:string"/>
      <xsd:element name="PROCESSID" nillable="true" type="xsd:string"/>
      <xsd:element name="CONFIRMBY" nillable="true" type="xsd:string"/>
      <xsd:element name="CONFIRMTIME" nillable="true" type="xsd:string"/>
      <xsd:element name="MEMO" nillable="true" type="xsd:string"/>
      <xsd:element name="FLAG" nillable="true" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="rec_CCDReocvered">
    <xsd:sequence>
      <xsd:element name="REFNO" nillable="true" type="xsd:string"/>
      <xsd:element name="VERSION" nillable="true" type="xsd:string"/>
      <xsd:element name="HOSPRGNO" nillable="true" type="xsd:string"/>
      <xsd:element name="ALLIANCEID" nillable="true" type="xsd:string"/>
      <xsd:element name="RECEIPTNO" nillable="true" type="xsd:string"/>
      <xsd:element name="NEW_PRICE" nillable="true" type="xsd:string"/>
      <xsd:element name="RECOVERED_AMOUNT" nillable="true" type="xsd:string"/>
      <xsd:element name="STATUS" nillable="true" type="xsd:string"/>
      <xsd:element name="FLAG" nillable="true" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== jordanchenWM/DOH_maven/DOH_maven/tess_src/MEDRCPTReply.xml
<?xml version="1.0" encoding="UTF-8"?>
<ReceiptReply xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MEDRCPTReply.xsd">
  <MesgInfo>
    <ProcessID>ProcessID</ProcessID>
    <SenderID>SenderID</SenderID>
    <ReceiverID>ReceiverID</ReceiverID>
    <DocumentType>DocumentType</DocumentType>
  </MesgInfo>
  <Header>
    <DocInfo>
      <DocNo>DocNo</DocNo>
    </DocInfo>
    <ReplyInfo>
      <Status>Status</Status>
    </ReplyInfo>
  </Header>
  <CrossRateInfo>
    <SourceReceiptNo>SourceReceiptNo</SourceReceiptNo>
    <OldRate>OldRate</OldRate>
    <NewRate>NewRate</NewRate>
    <Accamt>Accamt</Accamt>
    <SourceDisamt>SourceDisamt</SourceDisamt>
    <Memo>Memo</Memo>
  </CrossRateInfo>
  <UnitPriceInfo>
    <UNRECEIPTNO>UNRECEIPTNO</UNRECEIPTNO>
    <RECEIPTNO>RECEIPTNO</RECEIPTNO>
    <HOSPID>HOSPID</HOSPID>
    <HOSPRGNO>HOSPRGNO</HOSPRGNO>
    <PROCESSID>PROCESSID</PROCESSID>
    <CONFIRMBY>CONFIRMBY</CONFIRMBY>
    <CONFIRMTIME>CONFIRMTIME</CONFIRMTIME>
    <MEMO>MEMO</MEMO>
    <FLAG>FLAG</FLAG>
  </UnitPriceInfo>
  <CCD_RCPT_RECOVERED>
    <REFNO>REFNO</REFNO>
    <VERSION>VERSION</VERSION>
    <HOSPRGNO>HOSPRGNO</HOSPRGNO>
    <ALLIANCEID>ALLIANCEID</ALLIANCEID>
    <RECEIPTNO>RECEIPTNO</RECEIPTNO>
    <NEW_PRICE>NEW_PRICE</NEW_PRICE>
    <RECOVERED_AMOUNT>RECOVERED_AMOUNT</RECOVERED_AMOUNT>
    <STATUS>STATUS</STATUS>
    <FLAG>FLAG</FLAG>
  </CCD_RCPT_RECOVERED>
</ReceiptReply>
